// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteTokenReader is a Reader for the DeleteToken structure.
type DeleteTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/token] delete_token", response, response.Code())
	}
}

// NewDeleteTokenOK creates a DeleteTokenOK with default headers values
func NewDeleteTokenOK() *DeleteTokenOK {
	return &DeleteTokenOK{}
}

/*
DeleteTokenOK describes a response with status code 200, with default header values.

Access token successfully revoked.
*/
type DeleteTokenOK struct {
	Payload *DeleteTokenOKBody
}

// IsSuccess returns true when this delete token o k response has a 2xx status code
func (o *DeleteTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete token o k response has a 3xx status code
func (o *DeleteTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete token o k response has a 4xx status code
func (o *DeleteTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete token o k response has a 5xx status code
func (o *DeleteTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete token o k response a status code equal to that given
func (o *DeleteTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete token o k response
func (o *DeleteTokenOK) Code() int {
	return 200
}

func (o *DeleteTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenOK %s", 200, payload)
}

func (o *DeleteTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenOK %s", 200, payload)
}

func (o *DeleteTokenOK) GetPayload() *DeleteTokenOKBody {
	return o.Payload
}

func (o *DeleteTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTokenOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTokenBadRequest creates a DeleteTokenBadRequest with default headers values
func NewDeleteTokenBadRequest() *DeleteTokenBadRequest {
	return &DeleteTokenBadRequest{}
}

/*
DeleteTokenBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DeleteTokenBadRequest struct {
	Payload *DeleteTokenBadRequestBody
}

// IsSuccess returns true when this delete token bad request response has a 2xx status code
func (o *DeleteTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete token bad request response has a 3xx status code
func (o *DeleteTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete token bad request response has a 4xx status code
func (o *DeleteTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete token bad request response has a 5xx status code
func (o *DeleteTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete token bad request response a status code equal to that given
func (o *DeleteTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete token bad request response
func (o *DeleteTokenBadRequest) Code() int {
	return 400
}

func (o *DeleteTokenBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenBadRequest %s", 400, payload)
}

func (o *DeleteTokenBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenBadRequest %s", 400, payload)
}

func (o *DeleteTokenBadRequest) GetPayload() *DeleteTokenBadRequestBody {
	return o.Payload
}

func (o *DeleteTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTokenBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTokenUnauthorized creates a DeleteTokenUnauthorized with default headers values
func NewDeleteTokenUnauthorized() *DeleteTokenUnauthorized {
	return &DeleteTokenUnauthorized{}
}

/*
DeleteTokenUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type DeleteTokenUnauthorized struct {
	Payload *DeleteTokenUnauthorizedBody
}

// IsSuccess returns true when this delete token unauthorized response has a 2xx status code
func (o *DeleteTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete token unauthorized response has a 3xx status code
func (o *DeleteTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete token unauthorized response has a 4xx status code
func (o *DeleteTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete token unauthorized response has a 5xx status code
func (o *DeleteTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete token unauthorized response a status code equal to that given
func (o *DeleteTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete token unauthorized response
func (o *DeleteTokenUnauthorized) Code() int {
	return 401
}

func (o *DeleteTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenUnauthorized %s", 401, payload)
}

func (o *DeleteTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenUnauthorized %s", 401, payload)
}

func (o *DeleteTokenUnauthorized) GetPayload() *DeleteTokenUnauthorizedBody {
	return o.Payload
}

func (o *DeleteTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTokenUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTokenForbidden creates a DeleteTokenForbidden with default headers values
func NewDeleteTokenForbidden() *DeleteTokenForbidden {
	return &DeleteTokenForbidden{}
}

/*
DeleteTokenForbidden describes a response with status code 403, with default header values.

Token management endpoint is not configured.
*/
type DeleteTokenForbidden struct {
	Payload *DeleteTokenForbiddenBody
}

// IsSuccess returns true when this delete token forbidden response has a 2xx status code
func (o *DeleteTokenForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete token forbidden response has a 3xx status code
func (o *DeleteTokenForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete token forbidden response has a 4xx status code
func (o *DeleteTokenForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete token forbidden response has a 5xx status code
func (o *DeleteTokenForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete token forbidden response a status code equal to that given
func (o *DeleteTokenForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete token forbidden response
func (o *DeleteTokenForbidden) Code() int {
	return 403
}

func (o *DeleteTokenForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenForbidden %s", 403, payload)
}

func (o *DeleteTokenForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenForbidden %s", 403, payload)
}

func (o *DeleteTokenForbidden) GetPayload() *DeleteTokenForbiddenBody {
	return o.Payload
}

func (o *DeleteTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTokenForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTokenNotFound creates a DeleteTokenNotFound with default headers values
func NewDeleteTokenNotFound() *DeleteTokenNotFound {
	return &DeleteTokenNotFound{}
}

/*
DeleteTokenNotFound describes a response with status code 404, with default header values.

No active token to revoke for the given user.
*/
type DeleteTokenNotFound struct {
	Payload *DeleteTokenNotFoundBody
}

// IsSuccess returns true when this delete token not found response has a 2xx status code
func (o *DeleteTokenNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete token not found response has a 3xx status code
func (o *DeleteTokenNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete token not found response has a 4xx status code
func (o *DeleteTokenNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete token not found response has a 5xx status code
func (o *DeleteTokenNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete token not found response a status code equal to that given
func (o *DeleteTokenNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete token not found response
func (o *DeleteTokenNotFound) Code() int {
	return 404
}

func (o *DeleteTokenNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenNotFound %s", 404, payload)
}

func (o *DeleteTokenNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenNotFound %s", 404, payload)
}

func (o *DeleteTokenNotFound) GetPayload() *DeleteTokenNotFoundBody {
	return o.Payload
}

func (o *DeleteTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTokenNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTokenInternalServerError creates a DeleteTokenInternalServerError with default headers values
func NewDeleteTokenInternalServerError() *DeleteTokenInternalServerError {
	return &DeleteTokenInternalServerError{}
}

/*
DeleteTokenInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteTokenInternalServerError struct {
	Payload *DeleteTokenInternalServerErrorBody
}

// IsSuccess returns true when this delete token internal server error response has a 2xx status code
func (o *DeleteTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete token internal server error response has a 3xx status code
func (o *DeleteTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete token internal server error response has a 4xx status code
func (o *DeleteTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete token internal server error response has a 5xx status code
func (o *DeleteTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete token internal server error response a status code equal to that given
func (o *DeleteTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete token internal server error response
func (o *DeleteTokenInternalServerError) Code() int {
	return 500
}

func (o *DeleteTokenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenInternalServerError %s", 500, payload)
}

func (o *DeleteTokenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/token][%d] deleteTokenInternalServerError %s", 500, payload)
}

func (o *DeleteTokenInternalServerError) GetPayload() *DeleteTokenInternalServerErrorBody {
	return o.Payload
}

func (o *DeleteTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTokenInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteTokenBadRequestBody delete token bad request body
swagger:model DeleteTokenBadRequestBody
*/
type DeleteTokenBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this delete token bad request body
func (o *DeleteTokenBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token bad request body based on context it is used
func (o *DeleteTokenBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenBody delete token body
swagger:model DeleteTokenBody
*/
type DeleteTokenBody struct {

	// Email of the target user (mutually exclusive with `user_id`)
	Email string `json:"email,omitempty"`

	// ID of the target user (mutually exclusive with `email`)
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this delete token body
func (o *DeleteTokenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token body based on context it is used
func (o *DeleteTokenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenForbiddenBody delete token forbidden body
swagger:model DeleteTokenForbiddenBody
*/
type DeleteTokenForbiddenBody struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this delete token forbidden body
func (o *DeleteTokenForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token forbidden body based on context it is used
func (o *DeleteTokenForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenInternalServerErrorBody delete token internal server error body
swagger:model DeleteTokenInternalServerErrorBody
*/
type DeleteTokenInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this delete token internal server error body
func (o *DeleteTokenInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token internal server error body based on context it is used
func (o *DeleteTokenInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenNotFoundBody delete token not found body
swagger:model DeleteTokenNotFoundBody
*/
type DeleteTokenNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this delete token not found body
func (o *DeleteTokenNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token not found body based on context it is used
func (o *DeleteTokenNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenOKBody delete token o k body
swagger:model DeleteTokenOKBody
*/
type DeleteTokenOKBody struct {

	// email
	Email string `json:"email,omitempty"`

	// id
	ID string `json:"id_,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// reana token
	ReanaToken *DeleteTokenOKBodyReanaToken `json:"reana_token,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this delete token o k body
func (o *DeleteTokenOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateReanaToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteTokenOKBody) validateReanaToken(formats strfmt.Registry) error {
	if swag.IsZero(o.ReanaToken) { // not required
		return nil
	}

	if o.ReanaToken != nil {
		if err := o.ReanaToken.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deleteTokenOK" + "." + "reana_token")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deleteTokenOK" + "." + "reana_token")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this delete token o k body based on the context it is used
func (o *DeleteTokenOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateReanaToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteTokenOKBody) contextValidateReanaToken(ctx context.Context, formats strfmt.Registry) error {

	if o.ReanaToken != nil {

		if swag.IsZero(o.ReanaToken) { // not required
			return nil
		}

		if err := o.ReanaToken.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deleteTokenOK" + "." + "reana_token")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deleteTokenOK" + "." + "reana_token")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenOKBodyReanaToken delete token o k body reana token
swagger:model DeleteTokenOKBodyReanaToken
*/
type DeleteTokenOKBodyReanaToken struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this delete token o k body reana token
func (o *DeleteTokenOKBodyReanaToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token o k body reana token based on context it is used
func (o *DeleteTokenOKBodyReanaToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenOKBodyReanaToken) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenOKBodyReanaToken) UnmarshalBinary(b []byte) error {
	var res DeleteTokenOKBodyReanaToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteTokenUnauthorizedBody delete token unauthorized body
swagger:model DeleteTokenUnauthorizedBody
*/
type DeleteTokenUnauthorizedBody struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this delete token unauthorized body
func (o *DeleteTokenUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete token unauthorized body based on context it is used
func (o *DeleteTokenUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTokenUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTokenUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res DeleteTokenUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
