// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetQuotaUsageReader is a Reader for the GetQuotaUsage structure.
type GetQuotaUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQuotaUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetQuotaUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetQuotaUsageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetQuotaUsageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetQuotaUsageForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetQuotaUsageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetQuotaUsageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/quota] get_quota_usage", response, response.Code())
	}
}

// NewGetQuotaUsageOK creates a GetQuotaUsageOK with default headers values
func NewGetQuotaUsageOK() *GetQuotaUsageOK {
	return &GetQuotaUsageOK{}
}

/*
GetQuotaUsageOK describes a response with status code 200, with default header values.

Request succeeded. Raw resource quota limit is returned.
*/
type GetQuotaUsageOK struct {
	Payload *GetQuotaUsageOKBody
}

// IsSuccess returns true when this get quota usage o k response has a 2xx status code
func (o *GetQuotaUsageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get quota usage o k response has a 3xx status code
func (o *GetQuotaUsageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quota usage o k response has a 4xx status code
func (o *GetQuotaUsageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get quota usage o k response has a 5xx status code
func (o *GetQuotaUsageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get quota usage o k response a status code equal to that given
func (o *GetQuotaUsageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get quota usage o k response
func (o *GetQuotaUsageOK) Code() int {
	return 200
}

func (o *GetQuotaUsageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageOK %s", 200, payload)
}

func (o *GetQuotaUsageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageOK %s", 200, payload)
}

func (o *GetQuotaUsageOK) GetPayload() *GetQuotaUsageOKBody {
	return o.Payload
}

func (o *GetQuotaUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetQuotaUsageOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetQuotaUsageBadRequest creates a GetQuotaUsageBadRequest with default headers values
func NewGetQuotaUsageBadRequest() *GetQuotaUsageBadRequest {
	return &GetQuotaUsageBadRequest{}
}

/*
GetQuotaUsageBadRequest describes a response with status code 400, with default header values.

Request failed. The incoming data specification seems malformed.
*/
type GetQuotaUsageBadRequest struct {
	Payload *GetQuotaUsageBadRequestBody
}

// IsSuccess returns true when this get quota usage bad request response has a 2xx status code
func (o *GetQuotaUsageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get quota usage bad request response has a 3xx status code
func (o *GetQuotaUsageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quota usage bad request response has a 4xx status code
func (o *GetQuotaUsageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get quota usage bad request response has a 5xx status code
func (o *GetQuotaUsageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get quota usage bad request response a status code equal to that given
func (o *GetQuotaUsageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get quota usage bad request response
func (o *GetQuotaUsageBadRequest) Code() int {
	return 400
}

func (o *GetQuotaUsageBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageBadRequest %s", 400, payload)
}

func (o *GetQuotaUsageBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageBadRequest %s", 400, payload)
}

func (o *GetQuotaUsageBadRequest) GetPayload() *GetQuotaUsageBadRequestBody {
	return o.Payload
}

func (o *GetQuotaUsageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetQuotaUsageBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetQuotaUsageUnauthorized creates a GetQuotaUsageUnauthorized with default headers values
func NewGetQuotaUsageUnauthorized() *GetQuotaUsageUnauthorized {
	return &GetQuotaUsageUnauthorized{}
}

/*
GetQuotaUsageUnauthorized describes a response with status code 401, with default header values.

Request failed. Unauthorized.
*/
type GetQuotaUsageUnauthorized struct {
	Payload *GetQuotaUsageUnauthorizedBody
}

// IsSuccess returns true when this get quota usage unauthorized response has a 2xx status code
func (o *GetQuotaUsageUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get quota usage unauthorized response has a 3xx status code
func (o *GetQuotaUsageUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quota usage unauthorized response has a 4xx status code
func (o *GetQuotaUsageUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get quota usage unauthorized response has a 5xx status code
func (o *GetQuotaUsageUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get quota usage unauthorized response a status code equal to that given
func (o *GetQuotaUsageUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get quota usage unauthorized response
func (o *GetQuotaUsageUnauthorized) Code() int {
	return 401
}

func (o *GetQuotaUsageUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageUnauthorized %s", 401, payload)
}

func (o *GetQuotaUsageUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageUnauthorized %s", 401, payload)
}

func (o *GetQuotaUsageUnauthorized) GetPayload() *GetQuotaUsageUnauthorizedBody {
	return o.Payload
}

func (o *GetQuotaUsageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetQuotaUsageUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetQuotaUsageForbidden creates a GetQuotaUsageForbidden with default headers values
func NewGetQuotaUsageForbidden() *GetQuotaUsageForbidden {
	return &GetQuotaUsageForbidden{}
}

/*
GetQuotaUsageForbidden describes a response with status code 403, with default header values.

Request failed. Forbidden.
*/
type GetQuotaUsageForbidden struct {
	Payload *GetQuotaUsageForbiddenBody
}

// IsSuccess returns true when this get quota usage forbidden response has a 2xx status code
func (o *GetQuotaUsageForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get quota usage forbidden response has a 3xx status code
func (o *GetQuotaUsageForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quota usage forbidden response has a 4xx status code
func (o *GetQuotaUsageForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get quota usage forbidden response has a 5xx status code
func (o *GetQuotaUsageForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get quota usage forbidden response a status code equal to that given
func (o *GetQuotaUsageForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get quota usage forbidden response
func (o *GetQuotaUsageForbidden) Code() int {
	return 403
}

func (o *GetQuotaUsageForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageForbidden %s", 403, payload)
}

func (o *GetQuotaUsageForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageForbidden %s", 403, payload)
}

func (o *GetQuotaUsageForbidden) GetPayload() *GetQuotaUsageForbiddenBody {
	return o.Payload
}

func (o *GetQuotaUsageForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetQuotaUsageForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetQuotaUsageNotFound creates a GetQuotaUsageNotFound with default headers values
func NewGetQuotaUsageNotFound() *GetQuotaUsageNotFound {
	return &GetQuotaUsageNotFound{}
}

/*
GetQuotaUsageNotFound describes a response with status code 404, with default header values.

Request failed. User not found.
*/
type GetQuotaUsageNotFound struct {
	Payload *GetQuotaUsageNotFoundBody
}

// IsSuccess returns true when this get quota usage not found response has a 2xx status code
func (o *GetQuotaUsageNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get quota usage not found response has a 3xx status code
func (o *GetQuotaUsageNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quota usage not found response has a 4xx status code
func (o *GetQuotaUsageNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get quota usage not found response has a 5xx status code
func (o *GetQuotaUsageNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get quota usage not found response a status code equal to that given
func (o *GetQuotaUsageNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get quota usage not found response
func (o *GetQuotaUsageNotFound) Code() int {
	return 404
}

func (o *GetQuotaUsageNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageNotFound %s", 404, payload)
}

func (o *GetQuotaUsageNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageNotFound %s", 404, payload)
}

func (o *GetQuotaUsageNotFound) GetPayload() *GetQuotaUsageNotFoundBody {
	return o.Payload
}

func (o *GetQuotaUsageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetQuotaUsageNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetQuotaUsageInternalServerError creates a GetQuotaUsageInternalServerError with default headers values
func NewGetQuotaUsageInternalServerError() *GetQuotaUsageInternalServerError {
	return &GetQuotaUsageInternalServerError{}
}

/*
GetQuotaUsageInternalServerError describes a response with status code 500, with default header values.

Request failed. Internal server error.
*/
type GetQuotaUsageInternalServerError struct {
	Payload *GetQuotaUsageInternalServerErrorBody
}

// IsSuccess returns true when this get quota usage internal server error response has a 2xx status code
func (o *GetQuotaUsageInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get quota usage internal server error response has a 3xx status code
func (o *GetQuotaUsageInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quota usage internal server error response has a 4xx status code
func (o *GetQuotaUsageInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get quota usage internal server error response has a 5xx status code
func (o *GetQuotaUsageInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get quota usage internal server error response a status code equal to that given
func (o *GetQuotaUsageInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get quota usage internal server error response
func (o *GetQuotaUsageInternalServerError) Code() int {
	return 500
}

func (o *GetQuotaUsageInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageInternalServerError %s", 500, payload)
}

func (o *GetQuotaUsageInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/quota][%d] getQuotaUsageInternalServerError %s", 500, payload)
}

func (o *GetQuotaUsageInternalServerError) GetPayload() *GetQuotaUsageInternalServerErrorBody {
	return o.Payload
}

func (o *GetQuotaUsageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetQuotaUsageInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetQuotaUsageBadRequestBody get quota usage bad request body
swagger:model GetQuotaUsageBadRequestBody
*/
type GetQuotaUsageBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get quota usage bad request body
func (o *GetQuotaUsageBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get quota usage bad request body based on context it is used
func (o *GetQuotaUsageBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotaUsageBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotaUsageBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetQuotaUsageBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQuotaUsageForbiddenBody get quota usage forbidden body
swagger:model GetQuotaUsageForbiddenBody
*/
type GetQuotaUsageForbiddenBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get quota usage forbidden body
func (o *GetQuotaUsageForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get quota usage forbidden body based on context it is used
func (o *GetQuotaUsageForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotaUsageForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotaUsageForbiddenBody) UnmarshalBinary(b []byte) error {
	var res GetQuotaUsageForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQuotaUsageInternalServerErrorBody get quota usage internal server error body
swagger:model GetQuotaUsageInternalServerErrorBody
*/
type GetQuotaUsageInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get quota usage internal server error body
func (o *GetQuotaUsageInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get quota usage internal server error body based on context it is used
func (o *GetQuotaUsageInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotaUsageInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotaUsageInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetQuotaUsageInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQuotaUsageNotFoundBody get quota usage not found body
swagger:model GetQuotaUsageNotFoundBody
*/
type GetQuotaUsageNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get quota usage not found body
func (o *GetQuotaUsageNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get quota usage not found body based on context it is used
func (o *GetQuotaUsageNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotaUsageNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotaUsageNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetQuotaUsageNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQuotaUsageOKBody get quota usage o k body
swagger:model GetQuotaUsageOKBody
*/
type GetQuotaUsageOKBody struct {

	// limit
	Limit float64 `json:"limit,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// usage
	Usage float64 `json:"usage,omitempty"`
}

// Validate validates this get quota usage o k body
func (o *GetQuotaUsageOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get quota usage o k body based on context it is used
func (o *GetQuotaUsageOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotaUsageOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotaUsageOKBody) UnmarshalBinary(b []byte) error {
	var res GetQuotaUsageOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQuotaUsageUnauthorizedBody get quota usage unauthorized body
swagger:model GetQuotaUsageUnauthorizedBody
*/
type GetQuotaUsageUnauthorizedBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get quota usage unauthorized body
func (o *GetQuotaUsageUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get quota usage unauthorized body based on context it is used
func (o *GetQuotaUsageUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotaUsageUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotaUsageUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res GetQuotaUsageUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
