// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchQuotaReader is a Reader for the PatchQuota structure.
type PatchQuotaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchQuotaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPatchQuotaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchQuotaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchQuotaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPatchQuotaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchQuotaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchQuotaInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /api/quota] patch_quota", response, response.Code())
	}
}

// NewPatchQuotaOK creates a PatchQuotaOK with default headers values
func NewPatchQuotaOK() *PatchQuotaOK {
	return &PatchQuotaOK{}
}

/*
PatchQuotaOK describes a response with status code 200, with default header values.

Resource quota period fields successfully updated.
*/
type PatchQuotaOK struct {
}

// IsSuccess returns true when this patch quota o k response has a 2xx status code
func (o *PatchQuotaOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch quota o k response has a 3xx status code
func (o *PatchQuotaOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch quota o k response has a 4xx status code
func (o *PatchQuotaOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch quota o k response has a 5xx status code
func (o *PatchQuotaOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch quota o k response a status code equal to that given
func (o *PatchQuotaOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch quota o k response
func (o *PatchQuotaOK) Code() int {
	return 200
}

func (o *PatchQuotaOK) Error() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaOK", 200)
}

func (o *PatchQuotaOK) String() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaOK", 200)
}

func (o *PatchQuotaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchQuotaBadRequest creates a PatchQuotaBadRequest with default headers values
func NewPatchQuotaBadRequest() *PatchQuotaBadRequest {
	return &PatchQuotaBadRequest{}
}

/*
PatchQuotaBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type PatchQuotaBadRequest struct {
}

// IsSuccess returns true when this patch quota bad request response has a 2xx status code
func (o *PatchQuotaBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch quota bad request response has a 3xx status code
func (o *PatchQuotaBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch quota bad request response has a 4xx status code
func (o *PatchQuotaBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch quota bad request response has a 5xx status code
func (o *PatchQuotaBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this patch quota bad request response a status code equal to that given
func (o *PatchQuotaBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the patch quota bad request response
func (o *PatchQuotaBadRequest) Code() int {
	return 400
}

func (o *PatchQuotaBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaBadRequest", 400)
}

func (o *PatchQuotaBadRequest) String() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaBadRequest", 400)
}

func (o *PatchQuotaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchQuotaUnauthorized creates a PatchQuotaUnauthorized with default headers values
func NewPatchQuotaUnauthorized() *PatchQuotaUnauthorized {
	return &PatchQuotaUnauthorized{}
}

/*
PatchQuotaUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type PatchQuotaUnauthorized struct {
}

// IsSuccess returns true when this patch quota unauthorized response has a 2xx status code
func (o *PatchQuotaUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch quota unauthorized response has a 3xx status code
func (o *PatchQuotaUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch quota unauthorized response has a 4xx status code
func (o *PatchQuotaUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch quota unauthorized response has a 5xx status code
func (o *PatchQuotaUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this patch quota unauthorized response a status code equal to that given
func (o *PatchQuotaUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the patch quota unauthorized response
func (o *PatchQuotaUnauthorized) Code() int {
	return 401
}

func (o *PatchQuotaUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaUnauthorized", 401)
}

func (o *PatchQuotaUnauthorized) String() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaUnauthorized", 401)
}

func (o *PatchQuotaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchQuotaForbidden creates a PatchQuotaForbidden with default headers values
func NewPatchQuotaForbidden() *PatchQuotaForbidden {
	return &PatchQuotaForbidden{}
}

/*
PatchQuotaForbidden describes a response with status code 403, with default header values.

Quota functionality is not enabled.
*/
type PatchQuotaForbidden struct {
}

// IsSuccess returns true when this patch quota forbidden response has a 2xx status code
func (o *PatchQuotaForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch quota forbidden response has a 3xx status code
func (o *PatchQuotaForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch quota forbidden response has a 4xx status code
func (o *PatchQuotaForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch quota forbidden response has a 5xx status code
func (o *PatchQuotaForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this patch quota forbidden response a status code equal to that given
func (o *PatchQuotaForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the patch quota forbidden response
func (o *PatchQuotaForbidden) Code() int {
	return 403
}

func (o *PatchQuotaForbidden) Error() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaForbidden", 403)
}

func (o *PatchQuotaForbidden) String() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaForbidden", 403)
}

func (o *PatchQuotaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchQuotaNotFound creates a PatchQuotaNotFound with default headers values
func NewPatchQuotaNotFound() *PatchQuotaNotFound {
	return &PatchQuotaNotFound{}
}

/*
PatchQuotaNotFound describes a response with status code 404, with default header values.

User not found.
*/
type PatchQuotaNotFound struct {
}

// IsSuccess returns true when this patch quota not found response has a 2xx status code
func (o *PatchQuotaNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch quota not found response has a 3xx status code
func (o *PatchQuotaNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch quota not found response has a 4xx status code
func (o *PatchQuotaNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch quota not found response has a 5xx status code
func (o *PatchQuotaNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this patch quota not found response a status code equal to that given
func (o *PatchQuotaNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the patch quota not found response
func (o *PatchQuotaNotFound) Code() int {
	return 404
}

func (o *PatchQuotaNotFound) Error() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaNotFound", 404)
}

func (o *PatchQuotaNotFound) String() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaNotFound", 404)
}

func (o *PatchQuotaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchQuotaInternalServerError creates a PatchQuotaInternalServerError with default headers values
func NewPatchQuotaInternalServerError() *PatchQuotaInternalServerError {
	return &PatchQuotaInternalServerError{}
}

/*
PatchQuotaInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type PatchQuotaInternalServerError struct {
}

// IsSuccess returns true when this patch quota internal server error response has a 2xx status code
func (o *PatchQuotaInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch quota internal server error response has a 3xx status code
func (o *PatchQuotaInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch quota internal server error response has a 4xx status code
func (o *PatchQuotaInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch quota internal server error response has a 5xx status code
func (o *PatchQuotaInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this patch quota internal server error response a status code equal to that given
func (o *PatchQuotaInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the patch quota internal server error response
func (o *PatchQuotaInternalServerError) Code() int {
	return 500
}

func (o *PatchQuotaInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaInternalServerError", 500)
}

func (o *PatchQuotaInternalServerError) String() string {
	return fmt.Sprintf("[PATCH /api/quota][%d] patchQuotaInternalServerError", 500)
}

func (o *PatchQuotaInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
PatchQuotaBody patch quota body
swagger:model PatchQuotaBody
*/
type PatchQuotaBody struct {

	// Email of the target user (mutually exclusive with `user_id`)
	Email string `json:"email,omitempty"`

	// Length of the accounting window in months. Pass `null` to disable periodic accounting.
	// Minimum: 1
	QuotaPeriodMonths *int64 `json:"quota_period_months,omitempty"`

	// Timestamp of the active quota window start. Requires a periodic quota cadence to be set for the user.
	// Format: date-time
	QuotaPeriodStartAt *strfmt.DateTime `json:"quota_period_start_at,omitempty"`

	// Resource whose periodic quota is being updated. Only `cpu` is currently supported.
	// Required: true
	ResourceType *string `json:"resource_type"`

	// ID of the target user (mutually exclusive with `email`)
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this patch quota body
func (o *PatchQuotaBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateQuotaPeriodMonths(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateQuotaPeriodStartAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResourceType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchQuotaBody) validateQuotaPeriodMonths(formats strfmt.Registry) error {
	if swag.IsZero(o.QuotaPeriodMonths) { // not required
		return nil
	}

	if err := validate.MinimumInt("data"+"."+"quota_period_months", "body", *o.QuotaPeriodMonths, 1, false); err != nil {
		return err
	}

	return nil
}

func (o *PatchQuotaBody) validateQuotaPeriodStartAt(formats strfmt.Registry) error {
	if swag.IsZero(o.QuotaPeriodStartAt) { // not required
		return nil
	}

	if err := validate.FormatOf("data"+"."+"quota_period_start_at", "body", "date-time", o.QuotaPeriodStartAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *PatchQuotaBody) validateResourceType(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"resource_type", "body", o.ResourceType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this patch quota body based on context it is used
func (o *PatchQuotaBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PatchQuotaBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchQuotaBody) UnmarshalBinary(b []byte) error {
	var res PatchQuotaBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
