// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchQuotaParams creates a new PatchQuotaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchQuotaParams() *PatchQuotaParams {
	return &PatchQuotaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchQuotaParamsWithTimeout creates a new PatchQuotaParams object
// with the ability to set a timeout on a request.
func NewPatchQuotaParamsWithTimeout(timeout time.Duration) *PatchQuotaParams {
	return &PatchQuotaParams{
		timeout: timeout,
	}
}

// NewPatchQuotaParamsWithContext creates a new PatchQuotaParams object
// with the ability to set a context for a request.
func NewPatchQuotaParamsWithContext(ctx context.Context) *PatchQuotaParams {
	return &PatchQuotaParams{
		Context: ctx,
	}
}

// NewPatchQuotaParamsWithHTTPClient creates a new PatchQuotaParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchQuotaParamsWithHTTPClient(client *http.Client) *PatchQuotaParams {
	return &PatchQuotaParams{
		HTTPClient: client,
	}
}

/*
PatchQuotaParams contains all the parameters to send to the API endpoint

	for the patch quota operation.

	Typically these are written to a http.Request.
*/
type PatchQuotaParams struct {

	/* XQuotaManagementSecret.

	   REANA user quota management secret
	*/
	XQuotaManagementSecret string

	/* Data.

	   Data required to patch periodic quota fields (exactly one of `user_id` or `email` must be provided).
	*/
	Data PatchQuotaBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchQuotaParams) WithDefaults() *PatchQuotaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchQuotaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch quota params
func (o *PatchQuotaParams) WithTimeout(timeout time.Duration) *PatchQuotaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch quota params
func (o *PatchQuotaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch quota params
func (o *PatchQuotaParams) WithContext(ctx context.Context) *PatchQuotaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch quota params
func (o *PatchQuotaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch quota params
func (o *PatchQuotaParams) WithHTTPClient(client *http.Client) *PatchQuotaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch quota params
func (o *PatchQuotaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXQuotaManagementSecret adds the xQuotaManagementSecret to the patch quota params
func (o *PatchQuotaParams) WithXQuotaManagementSecret(xQuotaManagementSecret string) *PatchQuotaParams {
	o.SetXQuotaManagementSecret(xQuotaManagementSecret)
	return o
}

// SetXQuotaManagementSecret adds the xQuotaManagementSecret to the patch quota params
func (o *PatchQuotaParams) SetXQuotaManagementSecret(xQuotaManagementSecret string) {
	o.XQuotaManagementSecret = xQuotaManagementSecret
}

// WithData adds the data to the patch quota params
func (o *PatchQuotaParams) WithData(data PatchQuotaBody) *PatchQuotaParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the patch quota params
func (o *PatchQuotaParams) SetData(data PatchQuotaBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PatchQuotaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Quota-Management-Secret
	if err := r.SetHeaderParam("X-Quota-Management-Secret", o.XQuotaManagementSecret); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
