// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetQuotaLimitReader is a Reader for the SetQuotaLimit structure.
type SetQuotaLimitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetQuotaLimitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSetQuotaLimitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetQuotaLimitBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSetQuotaLimitUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetQuotaLimitForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetQuotaLimitNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetQuotaLimitInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/quota] set_quota_limit", response, response.Code())
	}
}

// NewSetQuotaLimitOK creates a SetQuotaLimitOK with default headers values
func NewSetQuotaLimitOK() *SetQuotaLimitOK {
	return &SetQuotaLimitOK{}
}

/*
SetQuotaLimitOK describes a response with status code 200, with default header values.

Resource quotas successfully set.
*/
type SetQuotaLimitOK struct {
	Payload *SetQuotaLimitOKBody
}

// IsSuccess returns true when this set quota limit o k response has a 2xx status code
func (o *SetQuotaLimitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set quota limit o k response has a 3xx status code
func (o *SetQuotaLimitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set quota limit o k response has a 4xx status code
func (o *SetQuotaLimitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set quota limit o k response has a 5xx status code
func (o *SetQuotaLimitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set quota limit o k response a status code equal to that given
func (o *SetQuotaLimitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set quota limit o k response
func (o *SetQuotaLimitOK) Code() int {
	return 200
}

func (o *SetQuotaLimitOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitOK %s", 200, payload)
}

func (o *SetQuotaLimitOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitOK %s", 200, payload)
}

func (o *SetQuotaLimitOK) GetPayload() *SetQuotaLimitOKBody {
	return o.Payload
}

func (o *SetQuotaLimitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetQuotaLimitOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetQuotaLimitBadRequest creates a SetQuotaLimitBadRequest with default headers values
func NewSetQuotaLimitBadRequest() *SetQuotaLimitBadRequest {
	return &SetQuotaLimitBadRequest{}
}

/*
SetQuotaLimitBadRequest describes a response with status code 400, with default header values.

Request failed. The incoming data specification seems malformed.
*/
type SetQuotaLimitBadRequest struct {
	Payload *SetQuotaLimitBadRequestBody
}

// IsSuccess returns true when this set quota limit bad request response has a 2xx status code
func (o *SetQuotaLimitBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set quota limit bad request response has a 3xx status code
func (o *SetQuotaLimitBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set quota limit bad request response has a 4xx status code
func (o *SetQuotaLimitBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this set quota limit bad request response has a 5xx status code
func (o *SetQuotaLimitBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this set quota limit bad request response a status code equal to that given
func (o *SetQuotaLimitBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the set quota limit bad request response
func (o *SetQuotaLimitBadRequest) Code() int {
	return 400
}

func (o *SetQuotaLimitBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitBadRequest %s", 400, payload)
}

func (o *SetQuotaLimitBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitBadRequest %s", 400, payload)
}

func (o *SetQuotaLimitBadRequest) GetPayload() *SetQuotaLimitBadRequestBody {
	return o.Payload
}

func (o *SetQuotaLimitBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetQuotaLimitBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetQuotaLimitUnauthorized creates a SetQuotaLimitUnauthorized with default headers values
func NewSetQuotaLimitUnauthorized() *SetQuotaLimitUnauthorized {
	return &SetQuotaLimitUnauthorized{}
}

/*
SetQuotaLimitUnauthorized describes a response with status code 401, with default header values.

Request failed. Unauthorized.
*/
type SetQuotaLimitUnauthorized struct {
	Payload *SetQuotaLimitUnauthorizedBody
}

// IsSuccess returns true when this set quota limit unauthorized response has a 2xx status code
func (o *SetQuotaLimitUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set quota limit unauthorized response has a 3xx status code
func (o *SetQuotaLimitUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set quota limit unauthorized response has a 4xx status code
func (o *SetQuotaLimitUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this set quota limit unauthorized response has a 5xx status code
func (o *SetQuotaLimitUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this set quota limit unauthorized response a status code equal to that given
func (o *SetQuotaLimitUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the set quota limit unauthorized response
func (o *SetQuotaLimitUnauthorized) Code() int {
	return 401
}

func (o *SetQuotaLimitUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitUnauthorized %s", 401, payload)
}

func (o *SetQuotaLimitUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitUnauthorized %s", 401, payload)
}

func (o *SetQuotaLimitUnauthorized) GetPayload() *SetQuotaLimitUnauthorizedBody {
	return o.Payload
}

func (o *SetQuotaLimitUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetQuotaLimitUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetQuotaLimitForbidden creates a SetQuotaLimitForbidden with default headers values
func NewSetQuotaLimitForbidden() *SetQuotaLimitForbidden {
	return &SetQuotaLimitForbidden{}
}

/*
SetQuotaLimitForbidden describes a response with status code 403, with default header values.

Request failed. Forbidden.
*/
type SetQuotaLimitForbidden struct {
	Payload *SetQuotaLimitForbiddenBody
}

// IsSuccess returns true when this set quota limit forbidden response has a 2xx status code
func (o *SetQuotaLimitForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set quota limit forbidden response has a 3xx status code
func (o *SetQuotaLimitForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set quota limit forbidden response has a 4xx status code
func (o *SetQuotaLimitForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this set quota limit forbidden response has a 5xx status code
func (o *SetQuotaLimitForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this set quota limit forbidden response a status code equal to that given
func (o *SetQuotaLimitForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the set quota limit forbidden response
func (o *SetQuotaLimitForbidden) Code() int {
	return 403
}

func (o *SetQuotaLimitForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitForbidden %s", 403, payload)
}

func (o *SetQuotaLimitForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitForbidden %s", 403, payload)
}

func (o *SetQuotaLimitForbidden) GetPayload() *SetQuotaLimitForbiddenBody {
	return o.Payload
}

func (o *SetQuotaLimitForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetQuotaLimitForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetQuotaLimitNotFound creates a SetQuotaLimitNotFound with default headers values
func NewSetQuotaLimitNotFound() *SetQuotaLimitNotFound {
	return &SetQuotaLimitNotFound{}
}

/*
SetQuotaLimitNotFound describes a response with status code 404, with default header values.

Request failed. User not found.
*/
type SetQuotaLimitNotFound struct {
	Payload *SetQuotaLimitNotFoundBody
}

// IsSuccess returns true when this set quota limit not found response has a 2xx status code
func (o *SetQuotaLimitNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set quota limit not found response has a 3xx status code
func (o *SetQuotaLimitNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set quota limit not found response has a 4xx status code
func (o *SetQuotaLimitNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this set quota limit not found response has a 5xx status code
func (o *SetQuotaLimitNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this set quota limit not found response a status code equal to that given
func (o *SetQuotaLimitNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the set quota limit not found response
func (o *SetQuotaLimitNotFound) Code() int {
	return 404
}

func (o *SetQuotaLimitNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitNotFound %s", 404, payload)
}

func (o *SetQuotaLimitNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitNotFound %s", 404, payload)
}

func (o *SetQuotaLimitNotFound) GetPayload() *SetQuotaLimitNotFoundBody {
	return o.Payload
}

func (o *SetQuotaLimitNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetQuotaLimitNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetQuotaLimitInternalServerError creates a SetQuotaLimitInternalServerError with default headers values
func NewSetQuotaLimitInternalServerError() *SetQuotaLimitInternalServerError {
	return &SetQuotaLimitInternalServerError{}
}

/*
SetQuotaLimitInternalServerError describes a response with status code 500, with default header values.

Request failed. Internal server error.
*/
type SetQuotaLimitInternalServerError struct {
	Payload *SetQuotaLimitInternalServerErrorBody
}

// IsSuccess returns true when this set quota limit internal server error response has a 2xx status code
func (o *SetQuotaLimitInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set quota limit internal server error response has a 3xx status code
func (o *SetQuotaLimitInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set quota limit internal server error response has a 4xx status code
func (o *SetQuotaLimitInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this set quota limit internal server error response has a 5xx status code
func (o *SetQuotaLimitInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this set quota limit internal server error response a status code equal to that given
func (o *SetQuotaLimitInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the set quota limit internal server error response
func (o *SetQuotaLimitInternalServerError) Code() int {
	return 500
}

func (o *SetQuotaLimitInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitInternalServerError %s", 500, payload)
}

func (o *SetQuotaLimitInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/quota][%d] setQuotaLimitInternalServerError %s", 500, payload)
}

func (o *SetQuotaLimitInternalServerError) GetPayload() *SetQuotaLimitInternalServerErrorBody {
	return o.Payload
}

func (o *SetQuotaLimitInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetQuotaLimitInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
SetQuotaLimitBadRequestBody set quota limit bad request body
swagger:model SetQuotaLimitBadRequestBody
*/
type SetQuotaLimitBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this set quota limit bad request body
func (o *SetQuotaLimitBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set quota limit bad request body based on context it is used
func (o *SetQuotaLimitBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitBadRequestBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SetQuotaLimitBody set quota limit body
swagger:model SetQuotaLimitBody
*/
type SetQuotaLimitBody struct {

	// Email of the target user (mutually exclusive with `user_id`)
	Email string `json:"email,omitempty"`

	// Raw quota limit to set
	// Required: true
	Limit *int64 `json:"limit"`

	// Resource type to set
	// Required: true
	ResourceType *string `json:"resource_type"`

	// ID of the target user (mutually exclusive with `email`)
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this set quota limit body
func (o *SetQuotaLimitBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResourceType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetQuotaLimitBody) validateLimit(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"limit", "body", o.Limit); err != nil {
		return err
	}

	return nil
}

func (o *SetQuotaLimitBody) validateResourceType(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"resource_type", "body", o.ResourceType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this set quota limit body based on context it is used
func (o *SetQuotaLimitBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SetQuotaLimitForbiddenBody set quota limit forbidden body
swagger:model SetQuotaLimitForbiddenBody
*/
type SetQuotaLimitForbiddenBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this set quota limit forbidden body
func (o *SetQuotaLimitForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set quota limit forbidden body based on context it is used
func (o *SetQuotaLimitForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitForbiddenBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SetQuotaLimitInternalServerErrorBody set quota limit internal server error body
swagger:model SetQuotaLimitInternalServerErrorBody
*/
type SetQuotaLimitInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this set quota limit internal server error body
func (o *SetQuotaLimitInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set quota limit internal server error body based on context it is used
func (o *SetQuotaLimitInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SetQuotaLimitNotFoundBody set quota limit not found body
swagger:model SetQuotaLimitNotFoundBody
*/
type SetQuotaLimitNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this set quota limit not found body
func (o *SetQuotaLimitNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set quota limit not found body based on context it is used
func (o *SetQuotaLimitNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitNotFoundBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SetQuotaLimitOKBody set quota limit o k body
swagger:model SetQuotaLimitOKBody
*/
type SetQuotaLimitOKBody struct {

	// limit
	Limit float64 `json:"limit,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// usage
	Usage float64 `json:"usage,omitempty"`
}

// Validate validates this set quota limit o k body
func (o *SetQuotaLimitOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set quota limit o k body based on context it is used
func (o *SetQuotaLimitOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitOKBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SetQuotaLimitUnauthorizedBody set quota limit unauthorized body
swagger:model SetQuotaLimitUnauthorizedBody
*/
type SetQuotaLimitUnauthorizedBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this set quota limit unauthorized body
func (o *SetQuotaLimitUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set quota limit unauthorized body based on context it is used
func (o *SetQuotaLimitUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetQuotaLimitUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetQuotaLimitUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res SetQuotaLimitUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
