// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetQuotaLimitParams creates a new SetQuotaLimitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetQuotaLimitParams() *SetQuotaLimitParams {
	return &SetQuotaLimitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetQuotaLimitParamsWithTimeout creates a new SetQuotaLimitParams object
// with the ability to set a timeout on a request.
func NewSetQuotaLimitParamsWithTimeout(timeout time.Duration) *SetQuotaLimitParams {
	return &SetQuotaLimitParams{
		timeout: timeout,
	}
}

// NewSetQuotaLimitParamsWithContext creates a new SetQuotaLimitParams object
// with the ability to set a context for a request.
func NewSetQuotaLimitParamsWithContext(ctx context.Context) *SetQuotaLimitParams {
	return &SetQuotaLimitParams{
		Context: ctx,
	}
}

// NewSetQuotaLimitParamsWithHTTPClient creates a new SetQuotaLimitParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetQuotaLimitParamsWithHTTPClient(client *http.Client) *SetQuotaLimitParams {
	return &SetQuotaLimitParams{
		HTTPClient: client,
	}
}

/*
SetQuotaLimitParams contains all the parameters to send to the API endpoint

	for the set quota limit operation.

	Typically these are written to a http.Request.
*/
type SetQuotaLimitParams struct {

	/* XQuotaManagementSecret.

	   REANA user quota management secret
	*/
	XQuotaManagementSecret string

	/* Data.

	   Data required to set quota limits (exactly one of `user_id` or `email` must be provided).
	*/
	Data SetQuotaLimitBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set quota limit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetQuotaLimitParams) WithDefaults() *SetQuotaLimitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set quota limit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetQuotaLimitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set quota limit params
func (o *SetQuotaLimitParams) WithTimeout(timeout time.Duration) *SetQuotaLimitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set quota limit params
func (o *SetQuotaLimitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set quota limit params
func (o *SetQuotaLimitParams) WithContext(ctx context.Context) *SetQuotaLimitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set quota limit params
func (o *SetQuotaLimitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set quota limit params
func (o *SetQuotaLimitParams) WithHTTPClient(client *http.Client) *SetQuotaLimitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set quota limit params
func (o *SetQuotaLimitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXQuotaManagementSecret adds the xQuotaManagementSecret to the set quota limit params
func (o *SetQuotaLimitParams) WithXQuotaManagementSecret(xQuotaManagementSecret string) *SetQuotaLimitParams {
	o.SetXQuotaManagementSecret(xQuotaManagementSecret)
	return o
}

// SetXQuotaManagementSecret adds the xQuotaManagementSecret to the set quota limit params
func (o *SetQuotaLimitParams) SetXQuotaManagementSecret(xQuotaManagementSecret string) {
	o.XQuotaManagementSecret = xQuotaManagementSecret
}

// WithData adds the data to the set quota limit params
func (o *SetQuotaLimitParams) WithData(data SetQuotaLimitBody) *SetQuotaLimitParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the set quota limit params
func (o *SetQuotaLimitParams) SetData(data SetQuotaLimitBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *SetQuotaLimitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Quota-Management-Secret
	if err := r.SetHeaderParam("X-Quota-Management-Secret", o.XQuotaManagementSecret); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
