// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WorkflowSubmissionResponse workflow submission response
//
// swagger:model WorkflowSubmissionResponse
type WorkflowSubmissionResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// run number
	RunNumber string `json:"run_number,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// user
	User string `json:"user,omitempty"`

	// validation warnings
	ValidationWarnings []*WorkflowSubmissionResponseValidationWarningsItems0 `json:"validation_warnings"`

	// workflow id
	WorkflowID string `json:"workflow_id,omitempty"`

	// workflow name
	WorkflowName string `json:"workflow_name,omitempty"`
}

// Validate validates this workflow submission response
func (m *WorkflowSubmissionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValidationWarnings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowSubmissionResponse) validateValidationWarnings(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationWarnings) { // not required
		return nil
	}

	for i := 0; i < len(m.ValidationWarnings); i++ {
		if swag.IsZero(m.ValidationWarnings[i]) { // not required
			continue
		}

		if m.ValidationWarnings[i] != nil {
			if err := m.ValidationWarnings[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("validation_warnings" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("validation_warnings" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this workflow submission response based on the context it is used
func (m *WorkflowSubmissionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateValidationWarnings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowSubmissionResponse) contextValidateValidationWarnings(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ValidationWarnings); i++ {

		if m.ValidationWarnings[i] != nil {

			if swag.IsZero(m.ValidationWarnings[i]) { // not required
				return nil
			}

			if err := m.ValidationWarnings[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("validation_warnings" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("validation_warnings" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowSubmissionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowSubmissionResponse) UnmarshalBinary(b []byte) error {
	var res WorkflowSubmissionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// WorkflowSubmissionResponseValidationWarningsItems0 workflow submission response validation warnings items0
//
// swagger:model WorkflowSubmissionResponseValidationWarningsItems0
type WorkflowSubmissionResponseValidationWarningsItems0 struct {

	// code
	Code string `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this workflow submission response validation warnings items0
func (m *WorkflowSubmissionResponseValidationWarningsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this workflow submission response validation warnings items0 based on context it is used
func (m *WorkflowSubmissionResponseValidationWarningsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowSubmissionResponseValidationWarningsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowSubmissionResponseValidationWarningsItems0) UnmarshalBinary(b []byte) error {
	var res WorkflowSubmissionResponseValidationWarningsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
